# ---------------------------------------------------------------------------------
# Restore CashCtrl Initial State
#
# This workflow restores the initial state of CashCtrl account.
#
# It is triggered:
# - nightly at 03:00 UTC,
# - manually via workflow dispatch.
# ---------------------------------------------------------------------------------

name: Restore CashCtrl Initial State

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

concurrency:
  # Within the same concurrency group, run only one job at a time
  # New jobs cancel existing pending jobs
  group: CashCtrl-test-account
  cancel-in-progress: false

jobs:
  restore:
    name: Restore Initial State
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.INSTALL_GITHUB }}
      CC_API_ORGANISATION: ${{ secrets.CC_API_ORGANISATION }}
      CC_API_KEY: ${{ secrets.CC_API_KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pyledger
        run: pip install git+https://x-access-token:${{ secrets.PYLEDGER_CI_ACCESS_TOKEN }}@github.com/macxred/pyledger.git@main

      - name: Install dependencies
        run: pip install pytest setuptools .

      - name: Run restore_initial_state.py script
        run: python -W error scripts/restore_initial_state.py
