on:
  # Run nightly tests at 03:00 UTC
  schedule:
    - cron: "0 3 * * *"
  # Manually triggered
  workflow_dispatch:

name: Restore CashCtrl initial state

concurrency:
  # Within the same concurrency group, run only one job at a time
  # New jobs cancel existing pending jobs
  group: CashCtrl-test-account
  cancel-in-progress: false

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: python:latest
    env:
      GITHUB_PAT: ${{ secrets.INSTALL_GITHUB }}
      CC_API_ORGANISATION: ${{ secrets.CC_API_ORGANISATION }}
      CC_API_KEY: ${{ secrets.CC_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup virtualenv
        run: |
          python -V  # Print out python version for debugging
          pip install virtualenv pytest
          virtualenv venv
          . venv/bin/activate

      - name: Install dependencies
        run: pip install pytest pandas setuptools .

      - name: Install package
        run: python setup.py develop

      - name: Run restore_initial_state.py script
        run: python -W error scripts/restore_initial_state.py
